services:
  mysql-db:
    container_name: ef-model-builder-db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql/
volumes:
  dbdata:    