openapi: 3.0.0
info:
  title: Email Manager API
  version: '1.0.0'
servers:
- url: http://base.addr/v1
paths:

  '/emails':
    
    post:
      tags: 
      - Emails
      summary: Create new email record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailDef'
      responses:
        200:
          description: Email record has been created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EmailId'
        400:
          description: Invalid request
          
  '/emails/{email_id}':
  
    parameters:
      - $ref: '#/components/parameters/EmailId'
      
    put:
      tags: 
      - Emails
      summary: Update email record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailDef'
      responses:
        200:
          description: Email record has been updates
        400:
          description: Invalid request
        404:
          description: Email not found
          
    delete:
      tags: 
      - Emails
      summary: Delete email record
      responses:
        200:
          description: Email record has been deleted
        404:
          description: Email not found
          
  '/emails/{email_id}/confirmation':
  
    parameters:
      - $ref: '#/components/parameters/EmailId'
      
    post:
      tags: 
      - Confirmation
      summary: Initialize confirmation process
      responses:
        200:
          description: Confirmation record has been started
        400:
          description: Invalid request
        404:
          description: Email not found
          
    delete:
      tags: 
      - Confirmation
      summary: Stop confirmation process
      responses:
        200:
          description: Confirmation record has been stopped
        400:
          description: Invalid request
        404:
          description: Email not found
          
    get:
      tags:
      - Confirmation
      summary: Get confirmation status
      responses:
        200:
          description: Confirmation record status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmationState'
        400:
          description: Invalid request
        404:
          description: Email not found
          
  '/sendings':
    
    post:
      tags: 
      - Sendings
      summary: Send message
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailSendingDef'
      responses:
        200:
          description: Email sending has been created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SendingId'
        400:
          description: Invalid request
    
components:

  parameters:
    
    EmailId:
      in: path
      name: email_id
      required: true
      description: Email record identifier
      schema:
        $ref: '#/components/schemas/EmailId'
  
  schemas:
  
    EmailSendingDef:
      type: object
      description: Email sending parameters
      oneOf:
      - $ref: '#/components/schemas/SimpleMessage'
      - $ref: '#/components/schemas/GenericMessage'
      properties:
        selection:
          $ref: '#/components/schemas/EmailLabels'
          
    SimpleMessage:
      type: object
      description: Simple message parameters
      properties:
        simpleContent:
          type: string
          description: Simple message content
          example: 'Hellow, Mike!'
          
    GenericMessage:
      type: object
      description: Generic message parameters
      properties:
        genericContent:
          type: object
          description: Generic message content
          properties:
            pattern:
              type: string
              description: Message pattern identifier
              example: 'ad'
            args:
              type: object
              description: Key-value template arguments
              additionalProperties: 
                type: string
              example:
                discount: 20
                addressing: 'mr'
  
    EmailDef:
      type: object
      description: Email write model
      properties:
        address:
          $ref: '#/components/schemas/EmailAddress'
        labels:
          $ref: '#/components/schemas/EmailLabels'
      required:
      - address
          
    EmailAddress:
      type: string 
      format: email
      description: Email address
      example: 'example@host.net'
      
    EmailLabels:
      type: object
      description: Key-value labels
      additionalProperties:
        type: string
      example:
        user: 'foo'
        group: 'bar'
        isMain: true
        
    EmailId:
      type: string
      format: guid
      description: Email record identifier
      example: 'c7bb1575e44c4b98a061bb63033fb438'
    
    SendingId:
      type: string
      format: guid
      description: Email sending identifier
      example: 'c7bb1575e44c4b98a061bb63033fb438'
      
    ConfirmationState:
      type: object
      description: Describes confirmation state
      properties:
        confirmed:
          type: boolean
          description: Confirmation factor 
          example: false
        step:
          type: string
          description: Confirmation process step
          enum:
          - created
          - email-sent
          - confirmed
          
      